site_name: My Docs
docs_dir: ./docs/
site_url: https://bqhoan.github.io/blogs/
theme:
  features:
    - content.tabs.link
  palette:
    primary: yellow
  name: material

plugins:
  - obsidian-interactive-graph
  - blogging:
      dirs:
        - post
      features:
        tags:
          index_page: tags.md
          insert: bottom
      time_format: ' %d-%m-%Y '

extra_javascript:
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js
  - assets/javascripts/interactive_graph.js

extra_css:
  - assets/stylesheets/obsidian_tags.css
  - assets/stylesheets/interactive_graph.css
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true