site_name: My Docs
site_url: https://bqhoan.github.io/blogs/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - blogging:
      dirs:
        - post
      features:
        tags:
          index_page: tags.md
          insert: bottom
      time_format: ' %d-%m-%Y '


markdown_extensions:
  - wikilinks