site_name: blogs
site_description: hoanbq's blog
site_url: https://bqhoan.github.io/blogs/
site_author: hoanbq


theme:
  name: material
  include_search_page: true
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Inter
    code: Source Code Pro
  features:
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.expand
    - navigation.indexes
    # navigation.instant      # WARN: breaks some javascripts
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - obsidian-interactive-graph
  - search
  - blogging:
      dirs:
        - post
      features:
        tags:
          index_page: tags.md
          insert: bottom
      time_format: ' %d-%m-%Y '

extra_javascript:
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js
  - assets/javascripts/interactive_graph.js

extra_css:
  - assets/stylesheets/obsidian_tags.css
  - assets/stylesheets/interactive_graph.css
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true